### ISSUE TITLE
Is there a packaged Docker image that can run the program？

### ISSUE THREAD

**Issue by Mn-blue** [Roger-random/SGVHAK_Rover#8]
Can this program run on Python 2 version now? I have installed the dependencies he needs countless times, but all have failed and I crashed. Is there a packaged Docker image that can run the program？

**Comment by Roger-random** [comment]
This was a personal learning project that hasn't been touched in years. Current level of functionality is unknown. Recent changes by GitHub Dependabot may have broken something.

I didn't know anything about Docker at the time.

**Comment by Mn-blue** [comment]
Thanks for your reply.
 I have successfully run the code for this project. I am using the latest Raspberry Pi OS (32 bit). It was released on December 5, 2023 and it only has a Python 3 environment. I must install Python 2 and Python 2 dev (to pip install spidev successfully).

**Comment by Roger-random** [comment]
Glad to hear you were successful!
